/**
 * @fileoverview Dev-only synthetic dataset: wipe mood/goals/tasks/habit domains (not settings) and
 * re-seed moods + journal notes, goals (reminders + history), day todos (reminder minutes), and habit selections
 * from 2020-01-01 through local today.
 *
 * Mood + notes are generated by a small **life simulation** (latent wellness, swings, occasional good/bad
 * events, era-aware context) so reads like a real person over the years—not a static template per day.
 *
 * Synthetic data is **opt-in**: `await globalThis.KairoSeed.rebuild()` in dev, or
 * {@link runFullDemoRebuild} / {@link ensureDevFullDemoDatasetCurrent} from code when you explicitly want it.
 */

import type { DayTodoItem, Goal, GoalHistory, MoodEntriesRecord, MoodGrade } from '../../types';
import { HABIT_IDS, type HabitId } from '../../lib/constants/habitsCatalog';
import { formatDateToISO, getToday, parseISODate } from '../../lib/utils/date';
import { logger } from '../../lib/security/logger';
import { normalizeNote, validateEntriesRecord } from '../model/entry';
import { ensureLocalPersistenceReady } from '../persistence/bootstrap';
import { storage } from './asyncStorage';
import { clearAllEntries, getAllEntries, setAllEntries } from './moodStorage';
import { getGoals, replaceAllGoalsForDev } from './goalsStorage';
import { wipeTasksStorageCompletely, bulkWriteDayTodoShardsForDev } from './tasksStorage';
import { clearAllHabitSelections, setAllHabitSelectionsRecord, type HabitSelectionsRecord } from './habitSelectionsStorage';
import { setTrackedHabitIds } from './habitTrackingStorage';
import { warmSessionStore } from './sessionStore';

const SEED_RANGE_START = '2020-01-01';
const DEMO_KEYS = ['kairo.demoSeeded', 'kairo.demoSeedVersion'] as const;

/** Bump when the synthetic dataset shape changes so dev installs refresh on next launch. */
export const FULL_DEMO_DATASET_VERSION = '2026-05-12-life-sim-v1';
export const FULL_DEMO_DATASET_VERSION_KEY = 'kairo.fullDemoDatasetVersion';

// --- PRNG (fast, seedable; tests use a fixed seed for stability) --------------------------------

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a += 0x6d2b79f5;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function createRebuildRng(): () => number {
  if (typeof process !== 'undefined' && process.env.NODE_ENV === 'test') {
    return mulberry32(0x9e3779b9);
  }
  const s = (Math.floor(Math.random() * 0xffffffff) ^ Date.now()) >>> 0;
  return mulberry32(s === 0 ? 0xfeedface : s);
}

function pick<T>(arr: readonly T[], rng: () => number): T {
  return arr[Math.min(arr.length - 1, Math.floor(rng() * arr.length))]!;
}

function clamp01(x: number): number {
  return Math.min(1, Math.max(0, x));
}

// --- Life simulation copy (journal beats) -------------------------------------------------------

const GOOD_SPIKES = [
  'Got unexpected good news at work.',
  'Had a real laugh with someone I love.',
  'Slept hard and woke up without an alarm.',
  'Finished something I had been avoiding for weeks.',
  'Someone reached out and it made the day lighter.',
  'Small win stacked into a big feeling of relief.',
  'Sun + coffee + nowhere to be — rare and good.',
  'Therapy session actually clicked today.',
  'Body felt cooperative for once.',
  'A walk fixed more than I thought it would.',
];

const BAD_SPIKES = [
  'Could not shut my brain off last night.',
  'Conflict I did not see coming — still rattled.',
  'Money stress hit out of nowhere.',
  'Health scare (probably fine) but my anxiety disagrees.',
  'Work piled on and I felt behind all day.',
  'Lonely in a room full of people.',
  'Family stuff. Not going to unpack it here.',
  'Burned out on screens and obligations.',
  'Missed a deadline — embarrassed and tired.',
  'Grief ambush. Anniversaries are weird.',
];

const MUNDANE_GOOD = [
  'Meal was simple but good.',
  'Inbox is not perfect but better.',
  'Made the bed. Small dignity win.',
  'Actually drank water like a person.',
  'Left work on time on purpose.',
  'Listened to a podcast and felt less alone in my head.',
  'Cleaned one corner of the apartment.',
  'Texted a friend I had been meaning to check on.',
];

const MUNDANE_NEUTRAL = [
  'Nothing dramatic — just moving through the day.',
  'Low drama, low sparkle.',
  'A lot of admin. Adulting.',
  'Tired in a normal way.',
  'Brain fog but I still showed up.',
  'Waiting on a few things outside my control.',
  'Kept promises to myself that nobody else would notice.',
];

const MUNDANE_HARD = [
  'Short fuse. Apologized where I needed to.',
  'Could not focus — tab hopping like a hobby.',
  'Body felt heavy; still did the minimum.',
  'Overthinking spiraled for an hour, then I reset.',
  'Skipped the thing I planned. Not proud, not the end.',
  'Cried in the car once. Felt a little better after.',
];

const ERA_2020_2021 = [
  'Pandemic brain is real — same four walls.',
  'Video calls for everything. Weirdly draining.',
  'Trying not to doomscroll the news.',
  'Masks, distance, and still trying to stay human.',
  'Grateful for small routines that stayed stable.',
];

const ERA_2022_2023 = [
  'Return-to-office whiplash.',
  'New role energy mixed with imposter noise.',
  'Trying boundaries with work hours again.',
  'Social battery is still recalibrating.',
  'Travel finally happened — overstimulated but happy.',
];

const ERA_2024_PLUS = [
  'Trying to build habits that survive busy seasons.',
  'Side project guilt vs rest — still negotiating.',
  'Feeling older in small ways. Not bad, just real.',
  'More selective with where I spend energy.',
  'Trying to name feelings earlier than I used to.',
];

const CLOSERS_UP = [
  'Grateful tonight.',
  'Hope I can carry a little of this into tomorrow.',
  'Logging it so I remember good weeks happen too.',
];

const CLOSERS_DOWN = [
  'Tomorrow can be smaller.',
  'No advice, just honesty.',
  'Still here. That counts.',
];

type SimDay = {
  dateKey: string;
  mood: MoodGrade;
  note: string;
  latent: number;
  createdAt: number;
  updatedAt: number;
};

type LifeSim = {
  latent: number;
  momentum: number;
  spikeKind: 'none' | 'up' | 'down';
  spikeLabel: string;
  spikeAge: number;
};

function initLifeSim(rng: () => number): LifeSim {
  return {
    latent: 0.45 + rng() * 0.22,
    momentum: (rng() - 0.5) * 0.2,
    spikeKind: 'none',
    spikeLabel: '',
    spikeAge: 999,
  };
}

function advanceLifeSim(sim: LifeSim, dateKey: string, rng: () => number): void {
  const y = Number(dateKey.slice(0, 4));

  sim.latent += (0.52 - sim.latent) * (0.018 + rng() * 0.022);
  sim.momentum *= 0.82;
  sim.momentum += (rng() - 0.5) * 0.095;
  sim.latent += sim.momentum * 0.055;

  if (y <= 2021 && rng() < 0.07) sim.latent -= 0.028 + rng() * 0.04;
  if (y >= 2022 && y <= 2023 && rng() < 0.045) sim.latent -= 0.015;

  if (rng() < 0.017) {
    sim.spikeKind = rng() < 0.48 ? 'down' : 'up';
    sim.spikeLabel = pick(sim.spikeKind === 'down' ? BAD_SPIKES : GOOD_SPIKES, rng);
    sim.latent += sim.spikeKind === 'down' ? -(0.12 + rng() * 0.2) : 0.08 + rng() * 0.16;
    sim.spikeAge = 0;
  } else {
    sim.spikeAge += 1;
  }

  if (rng() < 0.006) sim.momentum += (rng() - 0.5) * 0.45;

  sim.latent = clamp01(sim.latent);
}

function latentToMood(sim: LifeSim, rng: () => number): MoodGrade {
  const noise = (rng() - 0.5) * 0.13;
  const x = clamp01(sim.latent + noise + sim.momentum * 0.12);
  if (x >= 0.86) return rng() < 0.38 ? 'A+' : 'A';
  if (x >= 0.68) return rng() < 0.72 ? 'A' : 'B';
  if (x >= 0.48) return rng() < 0.55 ? 'B' : 'C';
  if (x >= 0.28) return rng() < 0.62 ? 'C' : 'D';
  return rng() < 0.55 ? 'D' : 'F';
}

function shuffle<T>(arr: readonly T[], rng: () => number): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    const t = a[i]!;
    a[i] = a[j]!;
    a[j] = t;
  }
  return a;
}

function eraFragments(dateKey: string, rng: () => number): string[] {
  const y = Number(dateKey.slice(0, 4));
  const out: string[] = [];
  if (y <= 2021 && rng() < 0.34) out.push(pick(ERA_2020_2021, rng));
  else if (y >= 2022 && y <= 2023 && rng() < 0.28) out.push(pick(ERA_2022_2023, rng));
  else if (y >= 2024 && rng() < 0.26) out.push(pick(ERA_2024_PLUS, rng));
  return out;
}

function buildLifeNote(dateKey: string, mood: MoodGrade, sim: LifeSim, rng: () => number): string {
  if (rng() < 0.1) {
    const micro =
      mood === 'A+' || mood === 'A'
        ? pick(['Good day.', 'Light.', 'Okay.'], rng)
        : mood === 'B'
          ? pick(['Meh but fine.', 'Nothing special.', 'Logging anyway.'], rng)
          : pick(['Rough day.', 'Low bandwidth.', 'Honest entry.'], rng);
    return normalizeNote(micro).slice(0, 200);
  }

  const parts: string[] = [];

  if (sim.spikeAge <= 4 && sim.spikeKind !== 'none' && rng() < 0.72) {
    parts.push(sim.spikeLabel);
  }

  parts.push(...eraFragments(dateKey, rng));

  if (mood === 'A+' || mood === 'A') {
    parts.push(pick(MUNDANE_GOOD, rng));
    if (rng() < 0.45) parts.push(pick(CLOSERS_UP, rng));
  } else if (mood === 'B') {
    parts.push(pick(MUNDANE_NEUTRAL, rng));
    if (rng() < 0.35) parts.push(pick(MUNDANE_GOOD, rng));
  } else if (mood === 'C') {
    parts.push(pick(MUNDANE_NEUTRAL, rng));
    if (rng() < 0.4) parts.push(pick(MUNDANE_HARD, rng));
  } else {
    parts.push(pick(MUNDANE_HARD, rng));
    if (rng() < 0.55) parts.push(pick(BAD_SPIKES, rng));
    if (rng() < 0.4) parts.push(pick(CLOSERS_DOWN, rng));
  }

  const raw = parts.filter(Boolean).join(' ');
  return normalizeNote(raw).slice(0, 200);
}

function simulateLifeDays(allKeys: readonly string[], rng: () => number): SimDay[] {
  const sim = initLifeSim(rng);
  const out: SimDay[] = [];

  for (const dateKey of allKeys) {
    advanceLifeSim(sim, dateKey, rng);
    const mood = latentToMood(sim, rng);
    const note = buildLifeNote(dateKey, mood, sim, rng);

    const [y, m, d] = dateKey.split('-').map(Number);
    const baseHour = mood === 'F' || mood === 'D' ? 1 + Math.floor(rng() * 3) : 9 + Math.floor(rng() * 8);
    const baseMin = Math.floor(rng() * 60);
    const base = new Date(y!, m! - 1, d!, baseHour, baseMin, Math.floor(rng() * 60)).getTime();
    const updatedAt = base + Math.floor(rng() * (mood === 'A+' || mood === 'A' ? 6 : 10) * 60 * 60 * 1000);

    out.push({ dateKey, mood, note, latent: sim.latent, createdAt: base, updatedAt });
  }
  return out;
}

// --- Day todos / reminders (contextual) ---------------------------------------------------------

const TODO_CARE = [
  'Drink water (for real)',
  'Stretch 10m',
  'Walk around the block',
  'Inbox 15m only',
  'Prep a simple dinner',
  'Sleep window: lights out',
  'Take meds / vitamins',
  'Journal 6 lines — no editing',
];

const TODO_SOCIAL = [
  'Text someone I miss',
  'Call mom / dad',
  'Schedule coffee with a friend',
  'Reply to the awkward email',
  'Say no to one thing',
];

const TODO_LIFE_ADMIN = [
  'Pay that bill',
  'Review bank transactions',
  'Book dentist',
  'Renew license / paperwork',
  'Groceries + snacks budget',
  'Laundry start-to-finish',
];

const TODO_WORK = [
  'Deep work 25m — phone in another room',
  'Write the scary task list',
  'One small ship: commit + push',
  'Prep for tomorrow’s meeting',
  'Close loops on 3 tickets',
];

function buildDayTodos(ctx: SimDay, rng: () => number): DayTodoItem[] | null {
  if (rng() > 0.48) return null;
  const n = rng() < 0.34 ? 2 : 1;
  const items: DayTodoItem[] = [];
  const pools: (readonly string[])[] = [];
  if (ctx.latent < 0.42) pools.push(TODO_CARE, TODO_LIFE_ADMIN);
  else pools.push(TODO_WORK, TODO_CARE, TODO_SOCIAL, TODO_LIFE_ADMIN);

  const REMINDER_MINUTES_POOL = [
    7 * 60 + 10 + Math.floor(rng() * 40),
    8 * 60 + 20 + Math.floor(rng() * 50),
    9 * 60 + Math.floor(rng() * 45),
    12 * 60 + 5 + Math.floor(rng() * 55),
    16 * 60 + 40 + Math.floor(rng() * 50),
    18 * 60 + 30 + Math.floor(rng() * 40),
    20 * 60 + 15 + Math.floor(rng() * 35),
  ];

  for (let i = 0; i < n; i++) {
    const pool = pick(pools, rng);
    const withRem = rng() < 0.55;
    items.push({
      id: `seed-todo-${ctx.dateKey}-${i}`,
      title: pick(pool, rng),
      done: rng() < 0.3,
      createdAt: ctx.createdAt + i * 1000,
      sortIndex: i,
      reminderMinutes: withRem ? pick(REMINDER_MINUTES_POOL, rng) : null,
    });
  }
  return items;
}

function buildHabitDay(ctx: SimDay, rng: () => number): HabitId[] | null {
  if (ctx.mood === 'F' && rng() < 0.55) return null;
  if (rng() > 0.55) return null;
  const k = 1 + Math.floor(rng() * 3);
  const pool = shuffle(HABIT_IDS, rng);
  return pool.slice(0, k) as HabitId[];
}

// --- Goals + history ----------------------------------------------------------------------------

function listLocalDayKeys(fromKey: string, toKey: string): string[] {
  const out: string[] = [];
  let cur = parseISODate(fromKey);
  const end = parseISODate(toKey);
  if (!Number.isFinite(cur.getTime()) || !Number.isFinite(end.getTime())) return out;
  while (cur.getTime() <= end.getTime()) {
    out.push(formatDateToISO(cur));
    cur = new Date(cur.getFullYear(), cur.getMonth(), cur.getDate() + 1);
  }
  return out;
}

function randomHistoryForHabit(
  goalId: string,
  fromKey: string,
  toKey: string,
  hitRate: number,
  noteChance: number,
  rng: () => number
): GoalHistory[] {
  const out: GoalHistory[] = [];
  for (const date of listLocalDayKeys(fromKey, toKey)) {
    if (rng() > hitRate) continue;
    const value = rng() < 0.9 ? 1 : 0;
    const note =
      value > 0 && rng() < noteChance
        ? normalizeNote(
            pick(
              [
                'Quick log after the reminder.',
                'Did the minimum and it helped.',
                'Almost skipped — glad I did not.',
                'Busy day but squeezed it in.',
                'Partner joined me today — easier.',
              ],
              rng
            )
          ).slice(0, 120)
        : '';
    const [y, m, d] = date.split('-').map(Number);
    const hourJitter = Math.floor(rng() * 4);
    const minJitter = Math.floor(rng() * 60);
    const createdAt = new Date(y!, m! - 1, d!, 8 + hourJitter, minJitter).getTime();
    out.push({
      id: `${goalId}:h:${date}`,
      date,
      value,
      note,
      createdAt,
    });
  }
  return out.slice(-800);
}

function sleepHoursHistory(goalId: string, fromKey: string, toKey: string, rng: () => number): GoalHistory[] {
  const out: GoalHistory[] = [];
  for (const date of listLocalDayKeys(fromKey, toKey)) {
    if (rng() > 0.76) continue;
    const clusterBad = rng() < 0.14;
    const hours = clusterBad ? 5.1 + rng() * 1.4 : 6.4 + rng() * 1.9;
    const value = Math.round(hours * 10) / 10;
    const [y, m, d] = date.split('-').map(Number);
    const createdAt = new Date(y!, m! - 1, d!, 9, 7 + Math.floor(rng() * 20)).getTime();
    out.push({
      id: `${goalId}:s:${date}`,
      date,
      value,
      note: rng() < 0.22 ? pick(['Wind-down alarm set.', 'Melatonin + no reels.', 'Slept on the couch by accident.'], rng) : '',
      createdAt,
    });
  }
  return out.slice(-900);
}

function buildSeedGoals(todayKey: string, now: number, rng: () => number): Goal[] {
  const habitFrom = '2020-02-01';

  const walkHistory = randomHistoryForHabit('seed-goal-walk', habitFrom, todayKey, 0.45 + rng() * 0.22, 0.32, rng);
  const readHistory = randomHistoryForHabit('seed-goal-read', habitFrom, todayKey, 0.32 + rng() * 0.22, 0.28, rng);
  const meditateHistory = randomHistoryForHabit('seed-goal-meditate', '2020-04-01', todayKey, 0.22 + rng() * 0.28, 0.42, rng);

  const savingsHistory: GoalHistory[] = [];
  for (const date of listLocalDayKeys('2020-01-01', todayKey)) {
    if (rng() > 0.11 + rng() * 0.06) continue;
    const [hy, hm, hd] = date.split('-').map(Number);
    savingsHistory.push({
      id: `seed-goal-save:${date}`,
      date,
      value: rng() < 0.68 ? 20 + Math.floor(rng() * 75) : 0,
      note: rng() < 0.24 ? pick(['Transfer reminder fired.', 'Skipped this week — tight month.', 'Small deposit anyway.'], rng) : '',
      createdAt: new Date(hy!, hm! - 1, hd!, 12, 4 + Math.floor(rng() * 25), 0).getTime(),
    });
  }

  const walkTitles = ['Walk most days', 'Move on purpose', 'Steps + sanity'];
  const readTitles = ['Read before bed', 'Twenty minutes reading', 'Put the phone down + read'];
  const meditateTitles = ['Short sit', 'Meditate (gentle)', '8 minutes quiet'];

  const goals: Goal[] = [
    {
      id: 'seed-goal-walk',
      type: 'habit',
      status: 'active',
      title: pick(walkTitles, rng),
      category: 'fitness',
      customCategory: null,
      accentColor: '#34C759',
      progress: { currentValue: 1, targetValue: 1, unit: 'session', frequency: 'daily' },
      reminder: {
        id: 'seed-rem-walk',
        enabled: true,
        frequency: 'weekdays',
        minutesFromMidnight: 7 * 60 + 15 + Math.floor(rng() * 35),
        weekdays: [1, 2, 3, 4, 5],
        interval: 1,
      },
      milestones: [],
      history: walkHistory,
      notes: normalizeNote(
        pick(
          [
            'Reminder is a nudge, not a verdict. Walk, stairs, or a mobility video all count.',
            'Trying not to moralize movement — some weeks I just need a short loop outside.',
          ],
          rng
        )
      ),
      durationDays: 120,
      createdAt: new Date(2020, 2, 14).getTime(),
      updatedAt: now,
      completedAt: null,
      archivedAt: null,
    },
    {
      id: 'seed-goal-read',
      type: 'habit',
      status: 'active',
      title: pick(readTitles, rng),
      category: 'learning',
      customCategory: null,
      accentColor: '#5AC8FA',
      progress: { currentValue: 1, targetValue: 1, unit: 'block', frequency: 'daily' },
      reminder: {
        id: 'seed-rem-read',
        enabled: rng() > 0.12,
        frequency: 'daily',
        minutesFromMidnight: 21 * 60 + 5 + Math.floor(rng() * 50),
        weekdays: [],
        interval: 1,
      },
      milestones: [],
      history: readHistory,
      notes: normalizeNote(
        pick(
          [
            'Night reminder: charger across the room, book in hand.',
            'If I miss a night, I do not “restart Monday.” I just read the next night.',
          ],
          rng
        )
      ),
      durationDays: 90,
      createdAt: new Date(2020, 5, 2).getTime(),
      updatedAt: now,
      completedAt: null,
      archivedAt: null,
    },
    {
      id: 'seed-goal-sleep',
      type: 'average',
      status: 'active',
      title: pick(['Sleep ~7.5h average', 'Protect sleep', 'Bedtime non-negotiable'], rng),
      category: 'wellness',
      customCategory: null,
      accentColor: '#AF52DE',
      progress: { currentValue: 7.2 + rng() * 0.25, targetValue: 7.5, unit: 'hours', frequency: 'daily' },
      reminder: {
        id: 'seed-rem-sleep',
        enabled: true,
        frequency: 'daily',
        minutesFromMidnight: 22 * 60 + 35 + Math.floor(rng() * 40),
        weekdays: [],
        interval: 1,
      },
      milestones: [],
      history: sleepHoursHistory('seed-goal-sleep', '2020-01-01', todayKey, rng),
      notes: normalizeNote(
        pick(
          [
            'Reminder is “start winding down,” not “be unconscious by 10:31.”',
            'Bad nights happen — I track sleep to notice patterns, not to punish myself.',
          ],
          rng
        )
      ),
      createdAt: new Date(2020, 8, 20).getTime(),
      updatedAt: now,
      completedAt: null,
      archivedAt: null,
    },
    {
      id: 'seed-goal-save',
      type: 'target',
      status: 'active',
      title: pick(['Emergency fund', 'Cash buffer', '“Oh no” money'], rng),
      category: 'finance',
      customCategory: null,
      accentColor: '#FF9500',
      progress: { currentValue: 3800 + Math.floor(rng() * 900), targetValue: 6000, unit: 'USD', frequency: 'monthly' },
      reminder: {
        id: 'seed-rem-save',
        enabled: true,
        frequency: 'weekly',
        minutesFromMidnight: 10 * 60 + Math.floor(rng() * 45),
        weekdays: [6],
        interval: 1,
      },
      milestones: [
        { id: 'ms1', title: '1 month buffer', targetValue: 2000, completedAt: new Date(2022, 3, 12).getTime(), sortIndex: 0 },
        { id: 'ms2', title: '3 month buffer', targetValue: 6000, completedAt: null, sortIndex: 1 },
      ],
      history: savingsHistory.slice(-600),
      notes: normalizeNote(
        pick(
          [
            'Weekly reminder: subscriptions + transfers. Boring adult stuff that lowers anxiety.',
            'Some weeks I can only save a little. That still counts.',
          ],
          rng
        )
      ),
      createdAt: new Date(2020, 10, 8).getTime(),
      updatedAt: now,
      completedAt: null,
      archivedAt: null,
    },
    {
      id: 'seed-goal-focus',
      type: 'project',
      status: 'active',
      title: pick(['Ship the app polish pass', 'Big work push (bounded)', 'Finish the scary milestone'], rng),
      category: 'work',
      customCategory: null,
      accentColor: '#0A84FF',
      progress: { currentValue: 45 + Math.floor(rng() * 35), targetValue: 100, unit: '%', frequency: 'weekly' },
      reminder: {
        id: 'seed-rem-focus',
        enabled: rng() > 0.08,
        frequency: 'weekdays',
        minutesFromMidnight: 13 * 60 + 20 + Math.floor(rng() * 50),
        weekdays: [1, 2, 3, 4, 5],
        interval: 1,
      },
      milestones: [
        { id: 'pm1', title: 'Navigation + tab bar', targetValue: 1, completedAt: new Date(2024, 2, 20).getTime(), sortIndex: 0 },
        { id: 'pm2', title: 'Calendar performance', targetValue: 1, completedAt: rng() < 0.4 ? new Date(2025, 0, 10).getTime() : null, sortIndex: 1 },
        { id: 'pm3', title: 'App Store checklist', targetValue: 1, completedAt: null, sortIndex: 2 },
      ],
      history: randomHistoryForHabit('seed-goal-focus', '2021-03-01', todayKey, 0.18 + rng() * 0.18, 0.45, rng),
      notes: normalizeNote(
        pick(
          [
            'Afternoon reminder: one 25m block, then I can touch grass.',
            'Progress notes are messy on purpose — this is a real project, not a highlight reel.',
          ],
          rng
        )
      ),
      createdAt: new Date(2021, 2, 15).getTime(),
      updatedAt: now,
      completedAt: null,
      archivedAt: null,
    },
    {
      id: 'seed-goal-meditate',
      type: 'habit',
      status: 'active',
      title: pick(meditateTitles, rng),
      category: 'mindfulness',
      customCategory: null,
      accentColor: '#63E6E2',
      progress: { currentValue: 1, targetValue: 1, unit: 'session', frequency: 'daily' },
      reminder: {
        id: 'seed-rem-meditate',
        enabled: true,
        frequency: 'daily',
        minutesFromMidnight: 7 * 60 + 40 + Math.floor(rng() * 35),
        weekdays: [],
        interval: 1,
      },
      milestones: [],
      history: meditateHistory,
      notes: normalizeNote(
        pick(
          [
            'Chair counts. So does lying down and breathing on purpose.',
            'Some days it is 2 minutes. Still not zero.',
          ],
          rng
        )
      ),
      durationDays: 60,
      createdAt: new Date(2020, 3, 18).getTime(),
      updatedAt: now,
      completedAt: null,
      archivedAt: null,
    },
    {
      id: 'seed-goal-done',
      type: 'habit',
      status: 'completed',
      title: '30-day sugar reset',
      category: 'health',
      customCategory: null,
      accentColor: '#FF3B30',
      progress: { currentValue: 30, targetValue: 30, unit: 'days', frequency: 'daily' },
      reminder: {
        id: 'seed-rem-done',
        enabled: false,
        frequency: 'daily',
        minutesFromMidnight: 20 * 60,
        weekdays: [],
        interval: 1,
      },
      milestones: [],
      history: randomHistoryForHabit('seed-goal-done', '2023-09-01', '2023-10-08', 0.78 + rng() * 0.12, 0.22, rng),
      notes: 'Completed. It was harder than I expected and I am proud I stayed kind to myself.',
      durationDays: 30,
      createdAt: new Date(2023, 8, 1).getTime(),
      updatedAt: new Date(2023, 9, 9).getTime(),
      completedAt: new Date(2023, 9, 9).getTime(),
      archivedAt: null,
    },
    {
      id: 'seed-goal-archived',
      type: 'target',
      status: 'archived',
      title: 'Old side project hours',
      category: 'creativity',
      customCategory: null,
      accentColor: '#8E8E93',
      progress: { currentValue: 40, targetValue: 120, unit: 'hours', frequency: 'monthly' },
      reminder: {
        id: 'seed-rem-arch',
        enabled: false,
        frequency: 'weekly',
        minutesFromMidnight: 19 * 60 + Math.floor(rng() * 40),
        weekdays: [0],
        interval: 1,
      },
      milestones: [],
      history: randomHistoryForHabit('seed-goal-archived', '2020-03-01', '2021-11-30', 0.06 + rng() * 0.08, 0.12, rng),
      notes: 'Archived. Life got loud; I might come back later without guilt.',
      createdAt: new Date(2020, 2, 1).getTime(),
      updatedAt: new Date(2021, 10, 15).getTime(),
      completedAt: null,
      archivedAt: new Date(2021, 10, 15).getTime(),
    },
  ];

  return goals;
}

export type FullDemoRebuildResult = {
  daysTotal: number;
  moodDays: number;
  todoDays: number;
  habitDayMarks: number;
  goals: number;
};

/**
 * Dev-only: **opt-in** helper — when you call it, runs {@link runFullDemoRebuild} if the store is empty,
 * legacy auto-demo markers exist, or {@link FULL_DEMO_DATASET_VERSION} is behind the bundled version.
 * Nothing invokes this on app launch; use it from tooling or tests when you want synthetic data refreshed.
 */
export async function ensureDevFullDemoDatasetCurrent(): Promise<void> {
  if (typeof __DEV__ === 'undefined' || !__DEV__) return;

  await ensureLocalPersistenceReady();

  const storedVersion = await storage.getItem(FULL_DEMO_DATASET_VERSION_KEY);
  if (storedVersion === FULL_DEMO_DATASET_VERSION) return;

  const legacyDemo = await storage.getItem('kairo.demoSeeded');
  const oldDemoVersion = await storage.getItem('kairo.demoSeedVersion');
  const hadLegacyAutoDemo = legacyDemo === '1' || (typeof oldDemoVersion === 'string' && oldDemoVersion.length > 0);

  const [entries, goals] = await Promise.all([getAllEntries(), getGoals()]);
  const entirelyEmpty = Object.keys(entries).length === 0 && goals.length === 0;

  const needsVersionedRefresh =
    typeof storedVersion === 'string' && storedVersion.length > 0 && storedVersion !== FULL_DEMO_DATASET_VERSION;

  if (!entirelyEmpty && !needsVersionedRefresh && !hadLegacyAutoDemo) return;

  await runFullDemoRebuild();
}

/**
 * Wipes mood entries, goals, tasks/day todos (+ shards), habit selections; clears demo-seed flags.
 * Re-seeds randomized data from {@link SEED_RANGE_START} through today (local).
 */
export async function runFullDemoRebuild(): Promise<FullDemoRebuildResult> {
  if (typeof __DEV__ === 'undefined' || !__DEV__) {
    throw new Error('runFullDemoRebuild is dev-only');
  }

  await ensureLocalPersistenceReady();

  await storage.multiRemove([...DEMO_KEYS]);
  await wipeTasksStorageCompletely();
  await clearAllEntries();
  await clearAllHabitSelections();

  const todayKey = getToday();
  const allKeys = listLocalDayKeys(SEED_RANGE_START, todayKey);
  const rng = createRebuildRng();
  const simDays = simulateLifeDays(allKeys, rng);

  const entries: MoodEntriesRecord = {};
  const shards: Record<string, DayTodoItem[]> = {};
  const habitRecord: HabitSelectionsRecord = {};

  let moodDays = 0;
  let todoDays = 0;
  let habitDayMarks = 0;

  for (const ctx of simDays) {
    entries[ctx.dateKey] = {
      date: ctx.dateKey,
      mood: ctx.mood,
      note: ctx.note,
      createdAt: ctx.createdAt,
      updatedAt: ctx.updatedAt,
    };
    moodDays += 1;

    const todos = buildDayTodos(ctx, rng);
    if (todos && todos.length > 0) {
      shards[ctx.dateKey] = todos;
      todoDays += 1;
    }

    const habits = buildHabitDay(ctx, rng);
    if (habits && habits.length > 0) {
      habitRecord[ctx.dateKey] = habits;
      habitDayMarks += 1;
    }
  }

  const now = Date.now();
  const goals = buildSeedGoals(todayKey, now, rng);

  await setAllEntries(validateEntriesRecord(entries));
  await replaceAllGoalsForDev(goals);
  await setTrackedHabitIds(shuffle(HABIT_IDS, rng).slice(0, Math.min(5, HABIT_IDS.length)) as HabitId[]);
  await setAllHabitSelectionsRecord(habitRecord);
  await bulkWriteDayTodoShardsForDev(shards);

  await storage.setItem(FULL_DEMO_DATASET_VERSION_KEY, FULL_DEMO_DATASET_VERSION);
  try {
    await warmSessionStore();
  } catch {
    // Non-fatal: RAM caches will repopulate on next read.
  }

  const summary: FullDemoRebuildResult = {
    daysTotal: allKeys.length,
    moodDays,
    todoDays,
    habitDayMarks,
    goals: goals.length,
  };
  logger.info('storage.fullDemoSeed.done', summary);
  return summary;
}
